# This file was generated by GoReleaser. DO NOT EDIT.
class Brudi < Formula
  desc "brudi CLI"
  homepage "https://brudi.com/"
  version "0.2.7"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/brudi/cli/releases/v0.2.7/brudi_0.2.7_macOS.tar.gz"
    sha256 "e39a6c3bb9355e3132b7e6c5b136a0e0172feadb3eaf83c60bf919795f66695e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "http://github.com/brudi/cli/releases/v0.2.7/brudi_0.2.7_linux.tar.gz"
      sha256 "5412793e7671212198a08319274abb734b338fba5ed062cd535eb84f1ec637c1"
    end
  end
  
  depends_on "docker"
  depends_on "git"

  def install
    bin.install "brudi"
  end

  test do
    system "brudi --version"
  end
end
