# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./custom_download_strategy"
class Cli < Formula
  desc "brudi CLI"
  homepage "https://brudi.com/"
  version "0.2.8-rc.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/brudi/cli/releases/download/v0.2.8-rc.5/cli_0.2.8-rc.5_macOS.tar.gz", :using => GitHubReleaseDownloadStrategy
    sha256 "8519961a2b99945e615d17a0eb1f61a515dd069d0c664e4d28b8a3b61bbdfb6d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/brudi/cli/releases/download/v0.2.8-rc.5/cli_0.2.8-rc.5_linux.tar.gz", :using => GitHubReleaseDownloadStrategy
      sha256 "d60f4dc26b923d626b7f9698ca09716c5a06f0b7cba93471ede81ac5a6585617"
    end
  end
  
  depends_on "docker"
  depends_on "git"

  def install
    bin.install "brudi"
  end

  test do
    system "brudi --version"
  end
end
