# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "brudi CLI"
  homepage "https://brudi.com/"
  version "0.2.5-rc.22"
  bottle :unneeded

  if OS.mac?
    url "http://github.mycompany.com/foo/bar/releases/v0.2.5-rc.22/cli_0.2.5-rc.22_macOS.tar.gz", :using => CurlDownloadStrategy.
    sha256 "6312bbcfb56da64a152417b7793f5ecd44b695b9430faaffd9b32e03e58080a5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "http://github.mycompany.com/foo/bar/releases/v0.2.5-rc.22/cli_0.2.5-rc.22_linux.tar.gz", :using => CurlDownloadStrategy.
      sha256 "10c586c1e68f2951a71afdde51ed0f24aa86b274ca91f5bcb8e2c9e044882ab8"
    end
  end
  
  depends_on "docker"
  depends_on "git"

  def install
    bin.install "brudi"
  end

  test do
    system "brudi --version"
  end
end
