# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Brudi < Formula
  desc "brudi CLI"
  homepage "https://brudi.com/"
  version "0.2.14"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/brudi/cli/releases/download/v0.2.14/brudi_0.2.14_macOS.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "65bb45b91dea941aca1107c28fc448e287df6f14205500c8041d3ed2d4bc1fe8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/brudi/cli/releases/download/v0.2.14/brudi_0.2.14_linux.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2a26347a3e14937c41880fbc2402cf6917896774ee2bca70c4e09cceaef60c81"
    end
  end

  def install
    bin.install "bin/brudi" => "brudi"
  end

  test do
    system "brudi --version"
  end
end
