# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./lib/custom_download_strategy"
class Cli < Formula
  desc "brudi CLI"
  homepage "https://brudi.com/"
  version "0.2.10"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/brudi/cli/releases/download/v0.2.10/cli_0.2.10_macOS.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "ecf0ff29ca3881f0aa372ac9c2e60c9e40eb64f3ef066e59ae9047a663a80242"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/brudi/cli/releases/download/v0.2.10/cli_0.2.10_linux.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5aebf6d32e6b7b9ac582d8f995a31175b302df171fcda3e120866d6eddfffb19"
    end
  end

  def install
    bin.install "bin/brudi" => "brudi"
  end

  test do
    system "brudi --version"
  end
end
